# Test your FastAPI endpoints

POST http://127.0.0.1:8000/sentiment-analysis
Content-Type: application/json

{
  "text": "I love my family"
}
###
POST http://127.0.0.1:8000/tokenizer
Content-Type: application/json

{
  "text": "I love my family"
}
